### ISSUE TITLE
reject plan use case

### ISSUE THREAD

**Issue by petsch0** [ida-arbeitszeit/arbeitszeitapp#1037]
similar to ApprovePlanUseCase, we need a RejectPlanUseCase so that social accounting has the possibility to reject plans.

afaics, to implement this, reject_plan use case, reject_plan_controller, reject_plan_presenter, some changes to html templating, tests, and changes to accountant routes are required.

I would also like to include in this issue new tiles/views in accountant dashboard for approved and rejected plans, just for the sake of completeness/documentation/availability.

**Comment by petsch0** [comment]
@seppeljordan do you see any option to avoid db migration when implementing this? I did not find one yet. The is_approved property from a plan unfortunately cannot be relied upon for this purpose afaics, because it is false as long as a plan is waiting. However, we now need data that can represent three values here: "waiting", "approved", and "rejected". I think two bools (is_approved and is_rejected) should be just fine. However, if we need to take into account possible future extensibility (not sure if this is relevant here though), it would probably be wiser to turn this information into a varchar/enum field now.

**Comment by sloschert** [comment]
I think the planner of the rejected plan should receive an email on plan rejection.

**Comment by Amittai-Aviram** [comment]
@petsch0 — Regarding the DB — isn't it important to record the date when a plan is rejected?
