### ISSUE TITLE
Prevent the `/company/register_hours_worked` view to re-submit already submitted forms

### ISSUE THREAD

**Issue by 4lm** [ida-arbeitszeit/arbeitszeitapp#1054]
Problem:

When reviewing #1051 I manually created hours worked test entries in `/company/register_hours_worked`. When I wanted to use the back button, my browser wanted to re-submit the actions of the already submitted forms.

Assessment:

This re-submitting (attempts) of already submitted forms is a behavioral anti-pattern in web app development and should be eliminated. Users should be able to use the back button in their browser without re-submitting a form. Fixing this also helps to reduce the number of accidentally re-submitted forms and lets the user more easily navigate the app.

Solution:

This behavior can easily be fixed by using the Post/Redirect/Get (PRG) design pattern [[1]](https://www.geeksforgeeks.org/post-redirect-get-prg-design-pattern/), [[2]](https://en.wikipedia.org/wiki/Post/Redirect/Get). In short, the pattern triggers a 302 redirect on POST, which triggers a GET by the browser of the target view. When using the back button, you never reach a route already sent. The route can stay the same, which means, concerning this issue: `POST` -> `/company/register_hours_worked` -> `302` redirect -> `/company/register_hours_worked` -> `GET` -> `/company/register_hours_worked`.

Questions:

- What do you think?
- If we introduce the PRG pattern, other form routes in the need of fixing might also exist. Do you know any? If so, shall we change them all in one PR or incrementally in multiple PRs?

**Comment by sloschert** [comment]
In general we tried to prevent re-submits, but in the mentioned PR I just forgot. Anyway, thanks for explaining the background, that will make it easier to not forget again.
I don't know of any other problematic route, but haven't checked them all.

**Comment by sloschert** [comment]
@4lm What is the status of this issue? I could not reproduce it in my browser - can it get closed?

**Comment by 4lm** [comment]
@sloschert, I checked, the issue still exists.

**Steps to reproduce:**

1. Sign in as a company
2. Go to `/company/register_hours_worked`
3. Register hours worked for a worker a first time
4. Register hours worked for a worker a second time
5. Hit the back button in your browser and a "Confirm Form Resubmission" message will appear (see screenshot below)

**Result of step 5:**

![image](https://github.com/user-attachments/assets/754d9a56-cae6-4cdd-9397-cf6f94da3f57)
