### ISSUE TITLE
Remove use of `@commit_changes` in GET request methods

### ISSUE THREAD

**Issue by 4lm** [ida-arbeitszeit/arbeitszeitapp#1084]
I started reviewing #1078, which may take a while to complete. There, I found an issue that is also present in other places in the source code, and which I therefore want to discuss in this RFC and not directly in the PR because I think it would deviate too much from the PR review. I have a question concerning the use of `@commit_changes` on GET request methods. I see this property is also used in other GET request view methods.

Example: https://github.com/ida-arbeitszeit/arbeitszeitapp/pull/1078/files#diff-cd0feb128dcca882b140b71c5409ef24ac8ecda6d80f137ea9e87ecf4f83bbfbR38

In my understanding, this property calls `db.session.commit()` after the wrapped function executes. If true, I don't understand why this is used in GET requests because the result of calling a resource with a GET request should never create, update or delete any database entries. GET requests should only be used to retrieve information. Only on POST, PATCH, PUT, and DELETE request methods does the use of `db.session.commit()` make sense, right? Or am I missing something here? Calling `db.session.commit()` would only make sense if we log user behavior straight to our database (tracking), which we don't do - right?

Please compare with the MDN documentation concerning GET requests:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET
- https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP

Money quote:

> [...] a method is safe if it leads to a read-only operation. Several common HTTP methods are safe: GET, HEAD, or OPTIONS. All safe methods are also idempotent [...] Even if safe methods have a read-only semantic, servers can alter their state: e.g. they can log or keep statistics. What is important here is that by calling a safe method, the client doesn't request any server change itself, and therefore won't create an unnecessary load or burden for the server. Browsers can call safe methods without fearing to cause any harm to the server; this allows them to perform activities like pre-fetching without risk.

**Comment by sloschert** [comment]
In theory, we should just be able to delete the `@commit_changes` decorator from GET request methods, because I agree that it should not be there. In practice, I would check the code before doing so, so that we do not accidentally delete some (misplaced) functionality.

**Comment by sloschert** [comment]
Problematic decorators should get deleted from the following places:

- [ ] `EndCooperationView` in `arbeitszeit_flask/views/end_cooperation_view.py`
- [ ] `company/my_cooperations` route
- [ ] `RegisterHoursWorkedView` in `arbeitszeit_flask/views/register_hours_worked_view.py`
- [ ] `RegisterPrivateConsumptionView`
- [ ] `RegisterProductiveConsumptionView`
- [ ] `RequestCooperationView`
- [ ] `RequestCoordinationTransferView`
- [ ] `ShowCoordinationTransferRequestView`
- [ ] `SignupAccountantView`
- [ ] `SignupCompanyView`
- [ ] `SignupMemberView`

**Comment by Amittai-Aviram** [comment]
Does anybody have an idea of why somebody had used that decorator with GET request methods in the first place?  Is there an institutional memory about this?
