### ISSUE TITLE
RFC Delete worker from company

### ISSUE THREAD

**Issue by sloschert** [ida-arbeitszeit/arbeitszeitapp#1092]
Currently it is not possible to undo a work relationship between worker and company.

I propose that companies should be able to delete workers from their list of associated workers. 

On company route `/company/invite_worker_to_company` there is currently a list of associated workers displayed. I propose to add a "delete" button to each worker entry.

After clicking that button and confirming a warning, the worker should be deleted from the list of associated workers and an informational email should be sent to the worker. 
 
This would be a minimal implementation, making it only possible for the company to delete workers from the list of associated workers and intentionally does not include any similar feature on the worker side.  

For simplicity and prioritization, I propose not to keep any history of worker's past workplaces or the company's past workers in the database for now. Instead, simply a row in the `jobs` table would get deleted.

What do you think?

**Comment by Amittai-Aviram** [comment]
I agree that it is a good starting point.  My main concern is the route:  the user interface for deleting an employee is in the page sent back from a request to `/company/invite_worker_to_company`.  This seems to me to be an odd place in which to have this feature.  I guess the manager does not necessarily have to invite a new employee, he or she only needs to request that page.  For now, perhaps this is OK.

**Comment by sloschert** [comment]
Yes, I agree that this is a odd place. Perhaps some changes to this route are necessary in the process.

(But yes, it is possible to access this page via GET, to receive the list of employees without inviting an employee.)

**Comment by sloschert** [comment]
FYI
My current plan is to create a new route (accepting GET and POST requests), called `company/select_worker_to_remove_from_company`.

The view class of this route implements two use cases (together with their controllers, presenter, etc.) of which the first one is still completely missing:

GET:

- SelectWorkerToRemoveFromCompany

POST:

- RemoveWorkerFromCompany

The integration with the current code would work by adding a link each of the current workers listed on the `invite_worker_to_company.html` page which would lead the user to the new route.

There, after the GET request, the user can check on the name and id of the worker it is about to remove. By click on a "remove" button the POST request is triggered.

**Comment by petsch0** [comment]
I think that this is a good way to go. I assume the invite_worker_to_company.html is currently the only place where the workers from a company are shown right?

**Comment by sloschert** [comment]
Yes
