### ISSUE TITLE
Icons are load from external server

### ISSUE THREAD

**Issue by philipbroistedt** [ida-arbeitszeit/arbeitszeitapp#656]
![grafik](https://user-images.githubusercontent.com/102257873/219113058-061740db-d857-4952-b19d-2e10b3d7d097.png)

**Comment by philipbroistedt** [comment]
Icons are load from external server use.font.awesome.com.

Users have to be informed or BETTER the icon shuld be hosted on the own server. Legal conditions have to be checked therefore.

**Comment by 4lm** [comment]
Closed by #1039
