### ISSUE TITLE
New Feature: Change member email address

### ISSUE THREAD

**Issue by seppeljordan** [ida-arbeitszeit/arbeitszeitapp#728]
Members should be able to change their email addresses. The following steps describe how this process should be handled:

1. Users should be able to request that their email address should be changed via the web interface. When requesting this change the user must provide the new email address in a web form. The system will reject the request if the email is already in use by any other account. 
2. If accepted then the user will receive an email with a confirmation link to their new email address. At the same time the system will send an email to the old email address, warning the user that the process to change their email address in the arbeitszeitapp was initiated. This email should contain an email address that lets the user contact an admin in case someone else is messing with their account. 
3. The confirmation link should lead to a page where the user can confirm the change. The user must provide their password for authentication purposes in this form. 
4. After the change was confirmed the system will use the new email address and "forget" about the old email address.

These steps were discussed in #702

**Comment by sloschert** [comment]
@seppeljordan Just to be sure: I will implement this in step 3, ok? "The user must provide their password for authentication purposes in this form."
